apiVersion: v1
kind: Service
metadata:
  name: {{ include "rust-server.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rust-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  selector:
    {{- include "rust-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: game-udp
      port: {{ .Values.service.gamePort }}
      targetPort: game-udp
      protocol: UDP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.gameNodePort }}
      nodePort: {{ .Values.service.gameNodePort }}
      {{- end }}
    - name: game-tcp
      port: {{ .Values.service.gamePort }}
      targetPort: game-tcp
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.gameNodePort }}
      nodePort: {{ .Values.service.gameNodePort }}
      {{- end }}
    - name: rcon
      port: {{ .Values.service.rconPort }}
      targetPort: rcon
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.rconNodePort }}
      nodePort: {{ .Values.service.rconNodePort }}
      {{- end }}
