apiVersion: v1
kind: Service
metadata:
  name: rust-server
spec:
  type: NodePort
  ports:
    - name: game-udp
      port: 28015
      targetPort: game-udp
      protocol: UDP
      nodePort: 30015
    - name: game-tcp
      port: 28015
      targetPort: game-tcp
      protocol: TCP
      nodePort: 30015
    - name: rcon
      port: 28016
      targetPort: rcon
      protocol: TCP
      nodePort: 30016
