name: Tests

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - 'test/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'docker/**'
      - 'test/**'
      - '.github/workflows/test.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bats:
    name: Shell Script Tests (bats)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: recursive

      - name: Install test dependencies
        run: sudo apt-get update && sudo apt-get install -y jq zip unzip

      - name: Run bats tests
        run: test/bats/bin/bats test/*.bats
